name: Deploy Application

on:
  push:
    branches: [ master ]  # Триггер на пуш в main ветку

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install nltk==3.9.1
          python -c "import nltk; nltk.download('punkt_tab')"
          pip install -r requirements-dev.txt

      - name: Run tests & qa
        run: |
          pytest
          mypy

      # deploy
      - name: Add SSH Private Key
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Execute Deployment Commands
        run: |
          ssh -o StrictHostKeyChecking=no -l leybovich-nikita 84.201.131.244 << 'EOF'
          cd kys_in_rest
          git pull
          source ./.venv/bin/activate
          pip install -r requirements.txt
          python -c "import nltk; nltk.download('punkt_tab')"
          pkill -f "python main.py" || true  # Игнорируем ошибку, если процесс не найден
          nohup python main.py > output.log 2>&1 &
          EOF