name: Stop Service

on:
  workflow_dispatch:  # Позволяет запускать вручную из интерфейса GitHub

jobs:
  stop-service:
    runs-on: ubuntu-latest
    steps:
      - name: Add SSH Private Key
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Execute Stop Commands
        run: |
          ssh -o StrictHostKeyChecking=no -l leybovich-nikita 84.201.131.244 << 'EOF'
          cd kys_in_rest
          source ./.venv/bin/activate
          pkill -f "python main.py"
          EOF 